#title in header
title: "Micah D. Cochran"

#main info
#owner
owner: "I am Micah D. Cochran"
email: mdcochra@uab.edu
info: "A MS Computer Science graduate student..."
#description
desc: "...at the University of Alabama at Birmingham.  I have years of 16 years experience working for a local Public Works Department with land development law and Geographic Information Systems (GIS).  My ideal job would be a software development job in a related field."

#menu
menu:
  Resume: /resume
#  About: /About

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
# placename: Earth
# placelink: https://en.wikipedia.org/wiki/Earth
github: https://github.com/micahcochran
# linkedin: https://linkedin.com/in/adisaktijrs
# twitter: https://twitter.com/adisaktijrs
# instagram: https://instagram.com/adisaktijrs
# stackoverflow: https://stackoverflow.com/story/tobiasreithmeier

# Misc
nanobar: /js/nanobar.min.js
switch_light: ☀️
switch_dark: 🌑

# Picture enlargement
# picjs: /js/pic.min.js

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io
