#title in header
title: "Micah D. Cochran, M.Sc."

#main info
#owner
owner: "I am Micah D. Cochran, M.Sc."
email: mdcochra@uab.edu
info: "I am software development professional available for hire."
#description
desc: "I have 16 years experience in land development law and Geographic Information Systems (GIS) working for a municipal Public Works Department.  My interests include Geographic Information Systems, Natural Language Processing, and the Semantic Web."

#menu
menu:
  Resume: /resume
  Projects: /resume/#Projects
#  About: /About

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
# placename: Earth
# placelink: https://en.wikipedia.org/wiki/Earth
github: https://github.com/micahcochran
linkedin: https://linkedin.com/in/micahcochran
# twitter: https://twitter.com/adisaktijrs
# instagram: https://instagram.com/adisaktijrs
# stackoverflow: https://stackoverflow.com/story/tobiasreithmeier

# Misc
nanobar: /js/nanobar.min.js
switch_light: ☀️
switch_dark: 🌑

# Picture enlargement
# picjs: /js/pic.min.js

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io
